spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  ## job.name ?? ??? job.name ??? NONE
  ## NONE ? ?? ?? ??? ?? x
  batch:
    job:
      names: ${job.name:NONE}

